import { Experience } from "@/types/types";

export const experiences: Experience[] = [
  {
    entity:"",
    position: "devWebFreelance.position",
    place: "devWebFreelance.place",	
    activity: "job",
    startDate: "2025",
    duration: "devWebFreelance.duration",
    description: "devWebFreelance.description",
    skills: "devWebFreelance.skills",
  },
  {
    entity:"",
    position: "devWeb.position",
    place: "devWeb.place",	
    activity: "study",
    startDate: "2024",
    duration: "devWeb.duration",
    description: "devWeb.description",
    skills: "devWeb.skills",
  },
  {
    entity: "Euronet",
    position: "entrepreneurship.position",
    place: "entrepreneurship.place",	
    activity: "entrepreneurship",
    startDate: "2022",
    endDate: "2024",
    duration: "entrepreneurship.duration",
    description: "entrepreneurship.description",
    skills: "entrepreneurship.skills",
  },
  {
    entity: "HarvardX",
    position: "dataScience.position",
    place: "dataScience.place",	
    activity: "study",
    startDate: "2021",
    endDate: "2022",
    duration: "dataScience.duration",
    description: "dataScience.description",
    skills: "dataScience.skills",
  },
  {
    entity: "Manufacture Cartier",
    position: "logistics.position",
    place: "logistics.place",	
    activity: "job",
    startDate: "2019",
    endDate: "2020",
    duration: "logistics.duration",
    description: "logistics.description",
    skills: "logistics.skills",
  },
  {
    entity: "Manufacture Cartier",
    position: "workshopScheduler.position",
    place: "workshopScheduler.place",	
    activity: "job",
    startDate: "2018",
    endDate: "2019",
    duration: "workshopScheduler.duration",
    description: "workshopScheduler.description",
    skills: "workshopScheduler.skills",
  },
  {
    entity: "Chaumet",
    position: "assistant.position",
    place: "assistant.place",	
    activity: "job",
    startDate: "2018",
    duration: "assistant.duration",
    description: "assistant.description",
    skills: "assistant.skills",
  },
  {
    entity: "UTBM",
    position: "studentA2I.position",
    place: "studentA2I.place",	
    activity: "study",
    startDate: "2017",
    endDate: "2018",
    duration: "studentA2I.duration",
    description: "",
  },
  { 
    entity: "UTSEUS",
    position: "studentLCIE.position",
    place: "studentLCIE.place",	
    activity: "study",
    startDate: "2017",
    duration: "studentLCIE.duration",
    description: "",
  },
  {
    entity: "UTBM",
    position: "studentIMSI.position",
    place: "studentIMSI.place",	
    activity: "study",
    startDate: "2014",
    endDate: "2018",
    duration: "studentIMSI.duration",
    description: "",
  },

]

