export default {
  nav: {
    project:"Projets",
    skills:"Compétences",
    stack:"Stack favorite",
    timeline:"Chronologie",
    about:"A propos"
  },
  cta: {
    title:"Hey 👋 ! Je suis",
    subtitle:"Développeur Front-end avec Next.js",
    description:"A la recherche de nouveaux challenges.",
    currently: "Me perfectionnant actuellement en Frontend (React / Next)",
    cv:"Mon CV",
  },
  project:{
    title:"Mes derniers projets",
    alaska:{
      name:"Alaska Pete's Roadhouse Grille",
      description:"Création d'un site d'un restaurant permettant de présenter les menus, passer des commandes, réserver une table et gérer les paiements.",
      date:"Février 2025",
    },
    amicale:{
      name:"Amicale du Don du Sang de Lyon",
      description:"Ce site, créé avec Docusaurus a pour objectif de présenter l'association, son fonctionnement (via la documentation) et son activité (via le blog).",
      date:"Décembre 2024 → Aujourd'hui",
    },
    cryptogalaxy:{
      name:"TheCryptoGalaxy",
      description:"TheCryptoGalaxy est un site rassemblant à un seul endroit les meilleurs outils et Dapp des écosystèmes blockchain les plus développés.",
      date:"2023 → Aujourd'hui",
    },
  },
  skills:{
    title:"Mes compétences",
    engineering:"Ingénierie",
    other:"Autres",
    logistic:"Logistique",
    language:"Langues",
    R:"R - Tests statistiques",
    workshopScheduling:"Ordonnancement",
    stockManagement:"Gestion de stock",
    projectManagement:"Gestion de projet",
    speach:"Parler en public",
    uiux:"Notion d'UI/UX",
    french:"Français",
    english:"Anglais",
    chinese:"Chinois",
    languageLevel3:"langue maternelle",
    languageLevel2:"compétences professionnelles",
    languageLevel1:"notions",
  },
  stack:{
    title:"Ma stack favorite",
    next:"Framework React moderne, Next m'offre des performances optimisées et un rendu rapide grâce au server-side rendering (SSR) et au static site generation (SSG). De plus, Next me permet de créer des applications fullstack.",
    tailwind:"Pour le styling, Tailwind offre un excellent compromis entre simplicité, rapidité et performances",
    typescript:"Grâce à typescript je crée un code robuste, tout en me facilitant la maintenance.",
    auth:"Flexible et facile à intégrer, la combination de BetterAuth et Prisma me permet de facilement gérer l'authentification et l'accès aux bases de données."
  },
  timeline:{
    title:"Chronologie",
    devWebFreelance:{
      position:"Développeur Web Freelance",
      place: "Lyon, France",
      duration: "1 an",
      description: "Lorem Ipsum",
      skills: "React, Next, PostgreSQL, Prisma, Docusaurus",
    },
    devWeb:{
      position:"Développeur Web",
      place: "Lyon, France",
      duration: "1 an",
      description: "Formation au développement web en autodidacte, en utilisant React et en particulier le framework Next.js. Création de sites et d’applications web. Gestion de l’authentification et de bases de données.",
      skills: "React, Next, PostgreSQL, Prisma, Docusaurus",
    },
    entrepreneurship:{
      position:"Projet Entrepreuneurial",
      place: "Lyon, France",
      duration: "2 ans",
      description: "Développement d’une plateforme pour la transparence des comptes publics dans l’objectif de rendre accessible aux contribuables les données sur le bon usage de l’argent public.",
      skills: "Web3, Blockchain, Finance Publique",
    },
    dataScience:{
      position:"Formation Data Science",
      place: "Chambéry, France",
      duration: "1 an",
      description: "Formation diplômante “Data Science with R” d’HarvardX. Data Science avec Python en machine learning et deep learning (Keras et TensorFlow). Création d’un logiciel d’achat vente d’actif numérique avec effet levier et stratégies optimisées par IA. Optimisation de portefeuille selon les concepts de Markovitz.",
      skills: "Python, R, Machine-learning, Deep-learning, Keras, Tensorflow, Scikit-learn",
    },
    logistics:{
      position:"Chargé de missions logistiques",
      place: "Fribourg, Suisse",
      duration: "1 an",
      description: "Refonte des flux de production de la ligne Or, flux tiré vs flux poussé, gestion des stocks, organisation de production et suivi d’efficience. Création d’indicateurs pour le pilotage de production. Responsabilité du portefeuille de projets de la manufacture.",
      skills: "Gestion de stocks, KPI, PM Office, Production, Logistique",
    },
    workshopScheduler:{
      position:"Ordonnanceur",
      place: "Fribourg, Suisse",
      duration: "1 an",
      description: "Ordonnancement des métiers d’usinage, polissage et assemblage pour la ligne Or de la manufacture. Gestion des stocks des produits semi-finis pour assurer la production des montres. Création de KPI pour assurer le suivi des quantités de lancements sur les nouveautés.",
      skills: "Ordonnancement, Gestion de stocks, KPI, SAP-APO, Production",
    },
    assistant:{
      position:"Stage Assistant chef de projet",
      place: "Paris, France",
      duration: "6 mois",
      description: "Calcul des leadtime et simulation des coûts de transports entre la France et les clients en Asie Pacifique, incluant les coûts de douanes en fonction des produits (normes CITES).",
      skills: "Gestion de projet, 5S, VBA, SAP, règlementations douanières pour les produits de luxe",
    },
    studentA2I:{
      position:"Master Affaires Industrielles Internationales (A2i)",
      place: "Belfort, France",
      duration: "1 an",
    },
    studentLCIE:{
      position:"Diplôme universitaire sur l’innovation et l’entrepreneuriat",
      place: "Shanghai, Chine",
      duration: "6 mois",
    },
    studentIMSI:{
      position:"Diplôme d’ingénieur en Logistique industrielle",
      place: "Belfort, France",
      duration: "4 ans",
    }
  },
  about:{
    title : "A propos",
    about1:"Développeur front end, je maîtrise le Framework",
    about2:"Je cherche à mettre mes compétences techniques et ma créativité au service de projets innovants. De plus, je suis avec attention les changements de paradigmes autour des technologies",
    about3:"blockchain et web 3.0",
    about4:"Je participe également  à des projets open source tels que le projet",
    about5:"Je suis une personne curieuse et désireuse de comprendre la complexité de notre monde. Je m'intéresse à différents domaines tels que la",
    about6:"géopolitique",
    about7:"l'économie et la finance",
    about7a:"ainsi que la.",
    about8:"sociologie.",
    about9:"Sur mon temps libre, j'aime découvrir la ",
    about10:"cuisine du monde",
    about11:", jouer au ",
    about12:" et je suis trésorier dans une association pour la promotion du ",
    about13:" Don du Sang",
  },
  footer:{
    contact:"Me contacter.",
    job:"Développeur Front-end avec",
    need:"N'hésitez pas à me contacter pour discuter de votre projet ou de vos besoins.",
    cv:"Mon CV",
  }
} as const