import { Experience } from "../lib/types";

export const experiences: Experience[] = [
  {
    id: "devWebFreelance",
    entity: "",
    position: "devWebFreelance.position",
    place: "devWebFreelance.place",
    activity: "job",
    startDate: "2025",
    duration: "devWebFreelance.duration",
    description:
      "devWebFreelance.description",
    skills: "devWebFreelance.skills",
  },
  {
    id: "devWeb",
    entity: "",
    position: "devWeb.position",
    place: "devWeb.place",
    activity: "study",
    startDate: "2024",
    duration: "devWeb.duration",
    description:
      "devWeb.description",
    skills: "devWeb.skills",
  },
  {
    id: "entrepreneurship",
    entity: "Euronet",
    position: "entrepreneurship.position",
    place: "entrepreneurship.place",
    activity: "entrepreneurship",
    startDate: "2022",
    endDate: "2024",
    duration: "entrepreneurship.duration",
    description:
      "entrepreneurship.description",
    skills: "entrepreneurship.skills",
  },
  {
    id: "dataScience",
    entity: "HarvardX",
    position: "dataScience.position",
    place: "dataScience.place",
    activity: "study",
    startDate: "2021",
    endDate: "2022",
    duration: "dataScience.duration",
    description:
      "dataScience.description",
    skills:
      "dataScience.skills",
  },
  {
    id: "logistics",
    entity: "Cartier",
    position: "logistics.position",
    place: "logistics.place",
    activity: "job",
    startDate: "2019",
    endDate: "2020",
    duration: "logistics.duration",
    description:
      "logistics.description",
    skills: "logistics.skills",
  },
  {
    id: "workshopScheduler",
    entity: "Cartier",
    position: "workshopScheduler.position",
    place: "workshopScheduler.place",
    activity: "job",
    startDate: "2018",
    endDate: "2019",
    duration: "workshopScheduler.duration",
    description:
      "workshopScheduler.description",
    skills: "workshopScheduler.skills",
  },
  {
    id: "assistant",
    entity: "Chaumet",
    position: "assistant.position",
    place: "assistant.place",
    activity: "job",
    startDate: "2018",
    duration: "assistant.duration",
    description:
      "assistant.description",
    skills:
      "assistant.skills",
  },
  {
    id: "studentA2I",
    entity: "UTBM",
    position: "studentA2I.position",
    place: "studentA2I.place",
    activity: "study",
    startDate: "2017",
    endDate: "2018",
    duration: "studentA2I.duration",
    description: "studentA2I.description",
    skills: "studentA2I.skills",
  },
  {
    id: "studentIMSI",
    entity: "UTSEUS",
    position: "studentIMSI.position",
    place: "studentIMSI.place",
    activity: "study",
    startDate: "2017",
    duration: "studentIMSI.duration",
    description: "studentIMSI.description",
    skills: "studentIMSI.skills",
  },
  {
    id: "studentLCIE",
    entity: "UTBM",
    position: "studentLCIE.position",
    place: "studentLCIE.place",
    activity: "study",
    startDate: "2014",
    endDate: "2018",
    duration: "studentLCIE.duration",
    description: "studentLCIE.description",
    skills: "studentLCIE.skills",
  },
];
